webapps/amicq/amicq/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import RedirectView
from home.views import Home

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^etudiant/', RedirectView.as_view(url='https://goo.gl/forms/gZoDCXfMHiBk7XXR2')),
    url(r'^student/', RedirectView.as_view(url='https://goo.gl/forms/gZoDCXfMHiBk7XXR2')),
    url(r'^', include('home.urls', namespace="home")),
    url(r'^donation/', include('payment.urls', namespace="payment")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webapps/amicq/home/urls.py
from django.conf.urls import url
import views


urlpatterns = [
    url(r'^$', views.Home.as_view(), name="home"),
    url(r'^statuts/$', views.statuts, name="statuts"),
    url(r'^annonces/$', views.annonces, name="annonces"),
    url(r'^joindre/$', views.joindre, name="joindre"),
    url(r'^mission/$', views.mission, name="mission"),
    url(r'^formulaire/$', views.formulaire, name="formulaire"),
    url(r'^nouvelles/$', views.news, name="news"),
    url(r'^telechargement/statuts/$', views.download, name="download_statuts")
]

webapps/amicq/payment/urls.py
from payment import views
from django.conf.urls import url

urlpatterns = [
    url(r'^$', views.donation, name="home"),
]

webapps/amicq/home/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

webapps/amicq/payment/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

webapps/amicq/home/views.py
import os

from django.shortcuts import redirect, render
from django.views.generic import View
from django.conf import settings
from django.http import HttpResponse


class Home(View):
    def get(self, request):
        return render(request, 'home/index.html')


def statuts(request):
    return render(request, 'home/StatutsRI.html')


def joindre(request):
    return render(request, 'home/Joindre.html')


def annonces(request):
    return render(request, 'home/annonces.html')


def mission(request):
    return render(request, 'home/mission.html')


def formulaire(request):
    return render(request, 'home/formulaire.html')


def download(request):
    path_to = os.path.join(settings.BASE_DIR, 'downloads', 'statuts.pdf')
    with open(path_to, 'r') as f:
        resp = HttpResponse(f.read(), content_type='application/pdf')
    resp['Content-Disposition'] = 'attachment; filename="AMICQ Statuts.pdf"'
    return resp


def news(request):
    return render(request, 'home/nouvelles.html')

webapps/amicq/payment/views.py
from django.http import Http404
from django.shortcuts import render
from django.template.context_processors import csrf
from django.conf import settings
import stripe
import math


def donation(request):

    if request.method == 'GET':
        stripe.api_key = settings.STRIPE_SECRET_KEY
        c = {'key': settings.STRIPE_PUBLISHABLE_KEY,
             }
        c.update(csrf(request))
        return render(request, 'payment/payments.html',c)

    elif request.method == 'POST':
        token = request.POST.get('stripeToken')
        payment_amount = request.POST.get('paymentAmount')
        stripe.api_key = settings.STRIPE_SECRET_KEY
        if token and payment_amount:
            try:

                #membership_fees = int(settings.MEMBERSHIP_FEES)*100
                charge = stripe.Charge.create(
                    amount=int(math.ceil(payment_amount)), # amount in cents, again
                    currency="cad",
                    card=token,
                    description="donation"
                )

                #request.user.paid=True
                #request.user.save()
                #certimail_payment.save()
                #send_payment_email(request, diagnostic_fees)
                #generate_invoice(request.user, float(diagnostic_fees)/100)

                return render(request, 'payment_succeeded.html')
            except stripe.InvalidRequestError, stripe.CardError:
                pass
        return render(request, 'payment_failed.html')
    else:
        raise Http404

webapps/amicq/home/templates/article.html
<!-- titre du texte -->
<section class="mbr-section" >
    <div class="mbr-section__container container mbr-section__container--first">
        <div class="mbr-header mbr-header--wysiwyg row">
            <div class="col-sm-8 col-sm-offset-2">
                <h3 class="mbr-header__text">{{title}}</h3>
                <p class="mbr-header__subtext">Par {{author}} publié le {{pub_date}}</p>
            </div>
        </div>
    </div>
</section>
<!-- corps du texte -->
<section class="mbr-section" >
    <div class="mbr-section__container container mbr-section__container--last">
        <div class="row">
            <div class="mbr-article mbr-article--wysiwyg col-sm-8 col-sm-offset-2">
                <p>{{content}}</p>
            </div>
        </div>
    </div>
</section>

webapps/amicq/home/templates/home/Joindre.html
<!DOCTYPE html>
<html>
<head>
  {% include 'home/head.html' %}
{% block head_scripts %}
  <script src="https://use.fontawesome.com/f46f0dfcfe.js"></script>
{% endblock %}
</head>
<body>
{% include 'home/navbar.html' %}

<section class="mbr-box mbr-section mbr-section--relative mbr-section--fixed-size mbr-section--full-height mbr-section--bg-adapted mbr-after-navbar" id="header1-7" style="background-color: rgb(61, 142, 185);">
    <div class="mbr-box__magnet mbr-box__magnet--sm-padding mbr-box__magnet--center-left">
        
        <div class="mbr-box__container mbr-section__container container">
            <div class="mbr-box mbr-box--stretched"><div class="mbr-box__magnet mbr-box__magnet--center-left">
                <div class="row"><div class=" col-sm-6 col-sm-offset-6">
                    <div class="mbr-hero animated fadeInUp">
                        <h1 class="mbr-hero__text">
                            <span>Courriel:</span><br>
                            <a target="_blank" href="mailto:info@amicq.ca">info@amicq.ca</a><br><br>
                            <span>Réseaux sociaux:</span><br>
                            <i class="fa fa-facebook-official"></i>
                            <a href="https://www.facebook.com/groups/309940995751320/" target="_blank">
                                Groupe Facebook de l'AMICQ
                            </a>
                            <br><br><br>
                        </h1>
                        
                    </div>
                    
                </div></div>
            </div></div>
        </div>
        {% comment %}
        <div class="mbr-arrow mbr-arrow--floating text-center">
            <div class="mbr-section__container container">
                <a class="mbr-arrow__link" href="#footer1-8"><i class="glyphicon glyphicon-menu-down"></i></a>
            </div>
        </div>
        {% endcomment %}
    </div>
</section>

{% include 'home/footer.html' %}
  
</body>
</html>

webapps/amicq/home/templates/home/StatutsRI.html
<!DOCTYPE html>
<html>
<head>
  {% include 'home/head.html' %}
{% block head_scripts %}
  <script src="https://use.fontawesome.com/f46f0dfcfe.js"></script>
{% endblock %}
</head>
<body>
{% include 'home/navbar.html' %}

<section class="mbr-box mbr-section mbr-section--relative mbr-section--fixed-size mbr-section--full-height mbr-section--bg-adapted mbr-parallax-background mbr-after-navbar" id="header1-13" style="background-color: lightseagreen;">
    <div class="mbr-box__magnet mbr-box__magnet--sm-padding mbr-box__magnet--center-left">
        
        <div class="mbr-box__container mbr-section__container container">
            <div class="mbr-box mbr-box--stretched">
                <div class="mbr-box__magnet mbr-box__magnet--center-left">
                    <div class="row">
                        <div class=" col-sm-6 col-sm-offset-6">
                            <div class="mbr-hero animated fadeInUp">
                                <h1 class="mbr-hero__text">
                                    STATUTS ET RÈGLEMENTS INTERIEURS<br>
                                    <a style="color: red; font-family: inherit; text-decoration:none;" href="">
                                        <i class="fa fa-large fa-file-pdf-o" style="font-size:1.8em"></i> (Téléchargement)
                                    </a><br>
                                </h1>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mbr-arrow mbr-arrow--floating text-center">
            <div class="mbr-section__container container">
                <a class="mbr-arrow__link" href="#footer1-14"><i class="glyphicon glyphicon-menu-down"></i></a>
            </div>
        </div>
    </div>
</section>

{% include 'home/footer.html' %}
  
  
</body>
</html>

webapps/amicq/home/templates/home/annonces.html
<!DOCTYPE html>
<html>
<head>
  {% include 'home/head.html' %}
{% block head_scripts %}
  <script src="https://use.fontawesome.com/f46f0dfcfe.js"></script>
{% endblock %}
</head>
<body>
{% include 'home/navbar.html' %}

<section class="mbr-box mbr-section mbr-section--relative mbr-section--fixed-size mbr-section--full-height mbr-section--bg-adapted mbr-after-navbar" id="header1-10" style="background-color: rgb(65, 168, 95);">
    <div class="mbr-box__magnet mbr-box__magnet--sm-padding mbr-box__magnet--center-left">
        
        <div class="mbr-box__container mbr-section__container container">
            <div class="mbr-box mbr-box--stretched">
                <div class="mbr-box__magnet mbr-box__magnet--center-left">
                    <div class="row">
                        <div class=" col-sm-6 col-sm-offset-6">
                            <div class="mbr-hero animated fadeInUp">
                                <h1 class="mbr-hero__text">
                                    <i class="fa fa-2X fa-newspaper-o"></i>&nbsp;<a href="{% url 'home:news' %}">Nouvelles</a><br><br>
                                    <i class="fa fa-2X fa-archive"></i>&nbsp;<a href="">Procès verbaux des réunions</a></h1>
                                <p class="mbr-hero__subtext">&nbsp;</p>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mbr-arrow mbr-arrow--floating text-center">
            <div class="mbr-section__container container">
                <a class="mbr-arrow__link" href="{% url 'home:news' %}"><i class="glyphicon glyphicon-menu-down"></i></a>
            </div>
        </div>
    </div>
</section>

{% include 'home/footer.html' %}
  
  
</body>
</html>

webapps/amicq/home/templates/home/footer.html
{% load static from staticfiles %}
<footer class="mbr-section mbr-section--relative mbr-section--fixed-size" id="footer1-11" style="background-color: rgb(68, 68, 68);">
    
    <div class="mbr-section__container container">
        <div class="mbr-footer mbr-footer--wysiwyg row" style="padding-top: 36.900000000000006px; padding-bottom: 36.900000000000006px;">
            <div class="col-sm-12">
                <p class="mbr-footer__copyright">Copyright (c) 2016 AMICQ </p>
            </div>
        </div>
    </div>
</footer>
{% include "home/scripts.html" %}

webapps/amicq/home/templates/home/formulaire.html
<!DOCTYPE html>
<html>
<head>
   {% load static from staticfiles %}
  {% include 'home/head.html' %}

</head>
<body>
{% include 'home/navbar.html' %}

<section class="engine"></section><section class="mbr-box mbr-section mbr-section--relative mbr-section--fixed-size mbr-section--full-height mbr-section--bg-adapted mbr-parallax-background mbr-after-navbar" id="header1-13" style="background-image: url(assets/images/img-0086-2592x1936-27.jpg);">
    <div class="mbr-box__magnet mbr-box__magnet--sm-padding mbr-box__magnet--center-left">
        
        <div class="mbr-box__container mbr-section__container container">
            <div class="mbr-box mbr-box--stretched"><div class="mbr-box__magnet mbr-box__magnet--center-left">
                <div class="row"><div class=" col-sm-12">
                    <div class="mbr-hero animated fadeInUp">
                        <div class="row">
                            <div class="col-sm-8 col-sm-offset-2" data-form-type="formoid">
                                <div class="mbr-header mbr-header--center mbr-header--std-padding">
                                    <h2 class="mbr-header__text" style="color: black; margin-top:70px">Formulaire d'inscription</h2>
                                </div>
                                <div data-form-alert="true">
                                    <div class="hide" data-form-alert-success="true">Super!</div>
                                </div>
                                <form action="#" method="post" data-form-title="Formulaire d'inscription">
                                    <input type="hidden" value="X+0zahVgIqHfk8yZPLARdTFr8XM/S/dCH+nHk2iM1YDMv+W5uA0jCWYZf8xfu/eS8OxLNo+QoRaXiTpSoPUGUdo3GEhC4KlNXUM9bfCE/eEzqvSGSOYsGyu8Len+Zlom" data-form-email="true">
                                    <div class="form-group">
                                        <input type="text" class="form-control" name="name" required="" placeholder="Nom" data-form-field="Nom">
                                    </div>
                                    <div class="form-group">
                                        <input type="email" class="form-control" name="email" required="" placeholder="Email*" data-form-field="Email">
                                    </div>
                                    <div class="form-group">
                                        <input type="tel" class="form-control" name="phone" placeholder="Téléphone" data-form-field="Phone">
                                    </div>
                                    <div class="form-group">
                                        <input type="text" class="form-control" name="profes" required="" placeholder="Profession" data-form-field="Profession">
                                    </div>
                                    <div class="form-group">
                                        <textarea class="form-control" name="message" rows="7" placeholder="Petite présentation (optionnel)" data-form-field="Message"></textarea>
                                    </div>
                                    <div class="mbr-buttons mbr-buttons--right"><button type="submit" class="mbr-buttons__btn btn btn-lg btn-danger">SOUMETTRE</button></div>
                                </form>
                            </div>
                        </div>
                        
                    </div>
                    
                </div></div>
            </div></div>
        </div>

    </div>
</section>

{% include 'home/footer.html' %}
<script src="{% static 'home/formoid/formoid.min.js' %}"></script>

</body>
</html>

webapps/amicq/home/templates/home/head.html
{% load static from staticfiles %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" href="/static/home/images/logo.png" type="image/x-icon">
  <meta name="description" content="">
  <title>AMICQ</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:700,400&amp;subset=cyrillic,latin,greek,vietnamese">
  <link rel="stylesheet" href="{% static 'home/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'home/animate.css/animate.min.css' %}">
  <link rel="stylesheet" href="{% static 'home/mobirise/css/style.css' %} ">
  <link rel="stylesheet" href="{% static 'home/dropdown-menu-plugin/style.css' %}">
  <link rel="stylesheet" href="{% static 'home/mobirise/css/mbr-additional.css' %}" type="text/css">

  <link rel="stylesheet" href="{% static 'home/mobirise-slider/style.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/navbar.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/custom.css' %}">
{% block head_scripts %}

{% endblock %}

webapps/amicq/home/templates/home/index.html
<!DOCTYPE html>
<html>
<head>
	{% load staticfiles %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" href="/static/home/images/logo.png" type="image/x-icon">
  <meta name="description" content="">
  <title>AMICQ</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:700,400&amp;subset=cyrillic,latin,greek,vietnamese">
  
  <link rel="stylesheet" href="{% static 'home/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'home/animate.css/animate.min.css' %}">
  <link rel="stylesheet" href="{% static 'home/mobirise/css/style.css' %} ">
  <link rel="stylesheet" href="{% static 'home/dropdown-menu-plugin/style.css' %}">
  <link rel="stylesheet" href="{% static 'home/mobirise/css/mbr-additional.css' %}" type="text/css">

  <link rel="stylesheet" href="{% static 'home/mobirise-slider/style.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/navbar.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/custom.css' %}">
</head>
<body>
{% include 'home/navbar.html' %}

<section class="mbr-slider mbr-section mbr-section--no-padding carousel slide" data-ride="carousel" data-wrap="true" data-interval="5000" id="slider-15" style="background-color: rgb(255, 255, 255);">
    <div class="mbr-section__container">
        <div>
            <ol class="carousel-indicators">
                <li data-app-prevent-settings="" data-target="#slider-15" class="active" data-slide-to="0"></li><li data-app-prevent-settings="" data-target="#slider-15" data-slide-to="1"></li><li data-app-prevent-settings="" data-target="#slider-15" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <div class="mbr-box mbr-section mbr-section--relative mbr-section--fixed-size mbr-section--bg-adapted item dark center mbr-section--full-height active" style="background-image: url(/static/home/images/img-0769-2592x1936-98-2000x1494-19.jpg);">
                    <div class="mbr-box__magnet mbr-box__magnet--center-center mbr-box__magnet--sm-padding mbr-after-navbar">
                        <div class="mbr-overlay" style="opacity: 0.6;"></div>
                        <div class=" container">
                            
                            <div class="row">
                                <div class=" col-md-8 col-md-offset-2">  

                                <div class="mbr-hero">
                                    <h1 class="mbr-hero__text" style="font-weight:400">Bienvenue sur le site de <br>
                                        <span style="font-weight:600">l'Amicale Ivoiro-Canadienne de Québec</span>
                                    </h1>

                                    
                                </div>
                                <div class="mbr-buttons btn-inverse mbr-buttons--center"> <a class="mbr-buttons__btn btn btn-lg btn-default" href="/formulaire">REJOIGNEZ L'AMICALE</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="mbr-box mbr-section mbr-section--relative mbr-section--fixed-size mbr-section--bg-adapted item dark center mbr-section--full-height" style="background-image: url(/static/home/images/img-0086-2592x1936-27-2000x1494-59.jpg);">
                    <div class="mbr-box__magnet mbr-box__magnet--center-left mbr-box__magnet--sm-padding mbr-after-navbar">
                        <div class="mbr-overlay" style="opacity: 0.6;"></div>
                        <div class=" container">
                            
                            <div class="row">
                                <div class=" col-md-6 col-md-offset-1">  

                                <div class="mbr-hero">
                                    

                                    
                                </div>
                                
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="mbr-box mbr-section mbr-section--relative mbr-section--fixed-size mbr-section--bg-adapted item dark center mbr-section--full-height" style="background-image: url(/static/home/images/img-0861-2592x1936-36-2000x1494-52.jpg);">
                    <div class="mbr-box__magnet mbr-box__magnet--center-center mbr-box__magnet--sm-padding mbr-after-navbar">
                                            
                        <div class=" container">
                            
                            <div class="row">
                                <div class=" col-md-8 col-md-offset-2">  

                                <div class="mbr-hero">
                                    

                                    
                                </div>
                                
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <a data-app-prevent-settings="" class="left carousel-control" role="button" data-slide="prev" href="#slider-15">
                <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
                <span class="sr-only">Précédent</span>
            </a>
            <a data-app-prevent-settings="" class="right carousel-control" role="button" data-slide="next" href="#slider-15">
                <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                <span class="sr-only">Suivant</span>
            </a>
        </div>
    </div>
</section>

{% include 'home/footer.html' %}
  
  
</body>
</html>

webapps/amicq/home/templates/home/mission.html
<!DOCTYPE html>
<html>
<head>
  {% include 'home/head.html' %}

</head>
<body>
{% include 'home/navbar.html' %}

<section class="mbr-box mbr-section mbr-section--relative mbr-section--fixed-size mbr-section--full-height mbr-section--bg-adapted mbr-after-navbar" id="header1-4" style="background-color: rgb(247, 218, 100);">
    <div class="mbr-box__magnet mbr-box__magnet--sm-padding mbr-box__magnet--center-left">
        
        <div class="mbr-box__container mbr-section__container container">
            <div class="mbr-box mbr-box--stretched"><div class="mbr-box__magnet mbr-box__magnet--center-left">
                <div class="row"><div class=" col-sm-6 col-sm-offset-6">
                    <div class="mbr-hero animated fadeInUp">
                        <h1 class="mbr-hero__text">Mission<br><br>Mot du Président</h1>
                        
                    </div>
                    
                </div></div>
            </div></div>
        </div>
        <div class="mbr-arrow mbr-arrow--floating text-center">
            <div class="mbr-section__container container">
                <a class="mbr-arrow__link" href="#sectionMission"><i class="glyphicon glyphicon-menu-down"></i></a>
            </div>
        </div>
    </div>
</section>
<section class="mbr-box mbr-section mbr-section--relative" id="sectionMission">
    <div class="container">
        <div class="mbr-box__magnet mbr-box__magnet--sm-padding">
            <div class="row">
                <div class="col-md-12">
                    <div class="page-header">
                        <h1 class="text-left">Missions</h1>
                    </div>
                    <ul class="list-group text-left" style="font-weight: 400; font-size:1.5em;">
                        <li class="list-group-item">Favoriser le rapprochement et l’approfondissement des relations entre les ivoiriens résidant à Québec et avec toute autre personne vivant à Québec ayant un intérêt en Côte d’ivoire ou pour la Côte d’ivoire</li>
                        <li class="list-group-item">Accueillir les nouveaux arrivants ivoiriens (immigrants, travailleurs, étudiants, etc.) à Québec, les orienter et les accompagner dans les premières démarches administratives</li>
                        <li class="list-group-item">Faciliter l’insertion de ses membres sur le marché du travail</li>
                        <li class="list-group-item">Promouvoir l’entraide et la solidarité dans la communauté ivoirienne à Québec</li>
                        <li class="list-group-item">Favoriser un brassage socioculturel avec la communauté québécoise et faire connaitre la côte d’ivoire en son sein</li>
                        <li class="list-group-item">Contribuer au développement socioéconomique du Québec et de la Côte d’ivoire</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

{% include 'home/footer.html' %}
  
</body>
</html>

webapps/amicq/home/templates/home/navbar.html
<section id="dropdown-menu-2btn-16">

    <nav class="navbar navbar-dropdown bg-color navbar-fixed-top" style="background-color:white">
    
        <div>

            <div class="navbar-brand">
                <a href="/" class="navbar-logo"><img src="/static/home/images/logo.png"  alt=""></a>
                <a class="text-white" href="">AMICQ</a>
            </div>
            
            <button style="color:orange" class="navbar-toggler pull-xs-right hidden-md-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
                ☰
            </button>

            <ul class="nav-dropdown collapse pull-xs-right navbar-toggleable-sm nav navbar-nav" id="exCollapsingNavbar">
                <li class="nav-item "><a class="nav-link link" href="/" aria-expanded="true">Accueil</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link link dropdown-toggle" href="/statuts" aria-expanded="true" data-toggle="dropdown-submenu">Association</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Vision</a>
                        <a class="dropdown-item" href="/mission">Mission et Valeurs</a>
                        <a class="dropdown-item" href="/statuts">Règlements intérieur</a>
                    </div>
                </li>
                <li class="nav-item"><a class="nav-link link" href="#" aria-expanded="true">Nos Programmes</a></li>
                <li class="nav-item"><a class="nav-link link" href="/annonces" aria-expanded="true">Nouvelles &amp; &nbsp;Annonces</a></li>
                <li class="nav-item"><a class="nav-link link" href="/joindre" aria-expanded="true">Nous joindre</a></li>
            </ul>

        </div>

    </nav>

</section>

webapps/amicq/home/templates/home/navbar_classic.html
<section class="mbr-navbar mbr-navbar--freeze mbr-navbar--absolute mbr-navbar--transparent mbr-navbar--sticky mbr-navbar--auto-collapse" id="menu-0">
    <div class="mbr-navbar__section mbr-section">
        <div class="mbr-section__container container">
            <div class="mbr-navbar__container">
                <div class="mbr-navbar__column mbr-navbar__column--s mbr-navbar__brand">
                    <span class="mbr-navbar__brand-link mbr-brand mbr-brand--inline">
                        <span class="mbr-brand__logo"><img src="/static/home/images/logo.png" class="mbr-navbar__brand-img mbr-brand__img"></span>
                        
                    </span>
                </div>
                <div class="mbr-navbar__hamburger mbr-hamburger"><span class="mbr-hamburger__line"></span></div>
                <div class="mbr-navbar__column mbr-navbar__menu">
                    <nav class="mbr-navbar__menu-box mbr-navbar__menu-box--inline-right">
                        <div class="mbr-navbar__column">
                            <ul class="mbr-navbar__items mbr-navbar__items--right float-left mbr-buttons mbr-buttons--freeze mbr-buttons--right btn-decorator mbr-buttons--active mbr-buttons--only-links"> <li class="mbr-navbar__item"><a class="mbr-buttons__link btn text-warning" href="/" target="_blank">Accueil</a></li> <li class="mbr-navbar__item"><a class="mbr-buttons__link btn text-warning" href="/statuts">Association</a></li> <li class="mbr-navbar__item"><a class="mbr-buttons__link btn text-warning" href="/annonces">Nouvelles &amp; Annonces</a></li> <li class="mbr-navbar__item"><a class="mbr-buttons__link btn text-warning" href="/mission">Mission</a></li> <li class="mbr-navbar__item"><a class="mbr-buttons__link btn text-warning" href="/joindre">Nous joindre</a></li>   </ul>
                            
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>

webapps/amicq/home/templates/home/nouvelles.html
<!DOCTYPE html>
<html>
<head>
  {% include 'home/head.html' %}
{% block head_scripts %}
  <script src="https://use.fontawesome.com/f46f0dfcfe.js"></script>
{% endblock %}
</head>
<body>
{% include 'home/navbar.html' %}

<section class="mbr-box mbr-section mbr-section--relative mbr-section--bg-adapted mbr-after-navbar" id="header1-10" style="color: black;">
    <div class="mbr-box__magnet mbr-box__magnet--sm-padding mbr-box__magnet--center">

        <div class="mbr-box__container mbr-section__container container">
            <div class="mbr-box mbr-box--stretched"><div class="mbr-box__magnet mbr-box__magnet--center">
                <div class="row">
                    <div class="col-sm-2 text-center">
                        <div class="hidden-xs" style="background-color:orange; min-height:40px; min-width:15%; padding:10px; position:fixed;">
                            <i class="fa fa-newspaper-o fa-2X"></i>
                        </div>
                        <div class="hidden visible-xs" style="background-color:orange; padding:inherit; padding-bottom: 10px; padding-top: 10px;">
                            <i class="fa fa-newspaper-o fa-2X"></i>
                        </div>
                    </div>
                    <div class=" col-sm-8">
                    <div class=" animated fadeInUp">
                        {% with title="Démarrage du site web de l'AMICQ" author="amicq" content="Bienvenue sur le site web de l'AMICQ. J'espère que vous apprécierez votre navigation." pub_date="24/02/17" %}

                            {% include "article.html" %}
                        {% endwith %}
                    </div>

                </div></div>
            </div></div>
        </div>
        <div class="mbr-arrow mbr-arrow--floating text-center">
            <div class="mbr-section__container container">
                <a class="mbr-arrow__link" href="{% url 'home:annonces' %}"><i class="glyphicon glyphicon-menu-down text-success"></i></a>
            </div>
        </div>
    </div>
</section>

{% include 'home/footer.html' %}


</body>
</html>